# config_path = "/etc/gitpack.conf" Hardcoded

# db_path = "/etc/gitpack.d/packages.db"
db_path = "/tmp/gitpack.db" # Debug

# cache_dir = "/var/cache/gitpack"
cache_dir = "/tmp/gitpack" # Debug

temp_dir = "/tmp/"

log_path = "/var/log/gitpack.log"

sources = [
    "https://github.com/",
    "https://gitlab.com/",
    "https://bitbucket.org/",
    "https://codeberg.org/"
]